### ISSUE TITLE
Visible deletion interface

### ISSUE THREAD

**Issue by KevinDCarlson** [ToposInstitute/CatColab#116]
Currently the only interface for deleting a cell is hitting backspace, which is a secret interaction. There should be something discoverable for this, maybe an 'X' that appears when you hover to the left or something, or just copy the dragging+item-edit-menu interface from Notion.

**Comment by epatters** [comment]
I like the Notion UI for this pretty well. In any case, we should think through this issue in conjunction with #19.

**Comment by epatters** [comment]
This issue will become more urgent with #135. At the moment, there is no way to delete analysis cells.
