### ISSUE TITLE
Duplicate an existing model

### ISSUE THREAD

**Issue by KevinDCarlson** [ToposInstitute/CatColab#117]
If I make an SIRD model and then open it with somebody and fiddle with it, it seems we're unavoidably editing the original model in the database and would have to manually revert it later. Need a "split" button that assigns a new ref to a model with the same content, something like that.

**Comment by KevinDCarlson** [comment]
@epatters @shaoweilin It seems like the new backend (#233  ?) doesn't yet fix this, right, since if I open someone else's model then either I'm editing the base model (In planet-sprite permissions mode) or I only get ephemeral edits (In lock-sprite permissions mode.) Hopefully it's easier now to build up an option to clone and edit persistently.

**Comment by shaoweilin** [comment]
Yeah I didn't work on the document model so I don't know what is the status
of this feature.

Shaowei

**Comment by epatters** [comment]
This feature has not been implemented but it should be easy enough to do so at this point. The main reason I haven't done it yet is that I don't have a menu to put the action in! That's another issue, which I will create.

If anyone wants to take this issue on now, say by adding a temporary toolbar button, let me know and I can outline the steps needed.
