### ISSUE TITLE
Unclear dropdown for choosing a logic

### ISSUE THREAD

**Issue by tim-at-topos** [ToposInstitute/CatColab#144]
The dropdown box for "Choose a logic" isn't clearly a dropdown (at least on Safari, MacOS), so the user might go searching around for where they can choose a logic. Possible solutions: add a border to the dropdown, or add a dropdown arrow symbol before/after the text.

Likely solved by https://github.com/ToposInstitute/CatColab/issues/52

**Comment by epatters** [comment]
Thanks for the report. I was indeed imagining that this issue would be solved by #52 but it's worth tracking as an issue in its own right.
