### ISSUE TITLE
Latency when changing route

### ISSUE THREAD

**Issue by KevinDCarlson** [ToposInstitute/CatColab#169]
It takes a slightly annoying amount of time to load up the analyis route when you instantiate your first analysis, especially since the user isn't meant to be aware they asked for a new route at that point. Evan and I just chatted about a few possibilities for improving this and similar issues:

- Don't bother with the "loading" page in between routes, and don't even blank the page in between routes if possible
- Consider pre-fetching Automerge hashes for all the analysis notebooks associated with a given model upon loading the model to avoid a server call in between routes
- Use `<Suspense>` to simulate loading faster by rendering things that don't have all their data yet.

**Comment by epatters** [comment]
At this point, we've got the low-hanging fruit: we don't display the distracting "Loading" text anywhere, and we start rendering the non-data-dependent parts of the page, such as toolbars and splitters, while the data is being loaded.

I'm going to call this resolved for now. Further reducing latency would require significant efforts beyond the scope of this generic issue.
