### ISSUE TITLE
Rust tests and docs in CI

### ISSUE THREAD

**Issue by epatters** [ToposInstitute/CatColab#26]
We should set up GitHub actions to:

- Run the tests of the Rust crate `catlog`
- Build and publish the docs of that crate
- Also run the tests of the bridge crate `catlog-wasm` (in `frontend` directory)

**Comment by olynch** [comment]
If the urgency of this is such that I could do it next week, I'm happy to do this.

**Comment by olynch** [comment]
We should also build/deploy a demo from CI.

**Comment by epatters** [comment]
> If the urgency of this is such that I could do it next week, I'm happy to do this.

Thanks Owen, that would be great. It can easily wait a week.

> We should also build/deploy a demo from CI.

I'm currently building and deploying the [demo](https://next.catcolab.org/) from Netlify. It works fine but the downside that most of the CI info is in Netlify rather GitHub. Perhaps we should have GitHub rather than Netlify in the driver's seat. Not urgent though by any means.

**Comment by epatters** [comment]
First bullet point is addressed by #36.

**Comment by epatters** [comment]
The remaining bullet points are addressed by #41 and #42. Thanks @olynch for this tour-de-force of CI work!
