### ISSUE TITLE
Scalar constants defined in model should be used in Julia service

### ISSUE THREAD

**Issue by epatters** [ToposInstitute/CatColab#284]
Currently a single constant,`diffusivity`, is hard-coded in the AlgJulia service.

Follow up issue to #283.

**Comment by epatters** [comment]
Actually, the situation seems to be more complicated. An item `diffusivity` is included in the [mapping](https://github.com/ToposInstitute/CatColab/blob/f2727c11e084d854023e9c2a379b2c574d959e95/packages/algjulia-service/src/decapodes-service/theory.jl#L28) but it doesn't seem to be used anywhere else. I guess it should be removed?

Instead, there is some logic [here](https://github.com/ToposInstitute/CatColab/blob/f2727c11e084d854023e9c2a379b2c574d959e95/packages/algjulia-service/src/decapodes-service/model.jl#L51) pertaining to scalars but I don't understand it. There is no connection between scalar multiplication operations and anonymous objects; such operations can be applied to named or anonymous objects. The scalar multiplication morphisms are the ones with [this morphism type](https://github.com/ToposInstitute/CatColab/blob/f2727c11e084d854023e9c2a379b2c574d959e95/packages/frontend/src/stdlib/theories.tsx#L432).

**Comment by quffaro** [comment]
The comment indeed is incorrect and should be removed. I think it comes from a brief interval in time when scalar multiplication and anonymous functions were more tightly linked.

The reason for the `:diffusivity` symbol in the mapping statement is so the corresponding entry in the model ([this example](http://localhost:5173/model/01936ac5-5fc3-7a21-a34b-fc1bc7d49358)) would map to an operation/function in the `sys_generate` function Julia-side.

It seems like this code is working accidentally. We don't distinguish by "morType" in the theory-building, we just check that there is a morphism which is linked to a corresponding id in the `scalars` JSON field. The resulting anonymous function is thrown into the `anons` dictionary and handled in the `sys_generate` function.

Is the correct implementation to have the `HomType` method for `add_to_theory!`  dispatch on the `morType` as well? It seems we'd still need to push curried `op2` functions onto `anons` until we have higher arity operations implemented.

**Comment by epatters** [comment]
> Is the correct implementation to have the `HomType` method for `add_to_theory!` dispatch on the `morType` as well? It seems we'd still need to push curried `op2` functions onto `anons` until we have higher arity operations implemented.

Yes, that sounds like the right approach to me. Right now, there will be two cases to handle in the dispatch, corresponding to the two morphism types in the `theories.tsx`. In the future, we might have others, I don't know. So dispatch seems like a good flexible mechanism to handle this.

**Comment by quffaro** [comment]
This feature was completed in [this commit](https://github.com/ToposInstitute/CatColab/commit/5689657e981ea3bd46231fd2445e2215efa52277). A @match statement was added to the morphism method for `add_to_model!` to check if the `morType` was `Nonscalar`. If it was, the name of the cell would be checked against a look-up table, but otherwise the name would be converted to a Symbol.

I move to close this issue.

**Comment by epatters** [comment]
Thanks Matt!
