### ISSUE TITLE
Reload page when a new theory has been selected

### ISSUE THREAD

**Issue by hamidahoderinwale** [ToposInstitute/CatColab#299]
If you have a blank doc and have already selected a theory, the page should automatically reload when you select a new one. This is also important for the widgets that depend on the selected theory.

[Solid documentation reference for reloading](https://docs.solidjs.com/solid-router/reference/response-helpers/reload
)

**Comment by epatters** [comment]
Sorry, I don't understand this. Why should the page need to reload? The change in theory should be handled reactively in the usual way without reloading the whole page, right?
