### ISSUE TITLE
Alternative interaction pattern: clicking

### ISSUE THREAD

**Issue by olynch** [ToposInstitute/CatColab#43]
In addition to shift-enter and the keyboard shortcuts, we should also be able to edit the notebook via clicking.

**Comment by epatters** [comment]
Agreed. My preference though is to keep any buttons for adding cells, moving them, etc as unobtrusive as possible.

**Comment by olynch** [comment]
See #50 for a proposed "new cell" click target.

**Comment by epatters** [comment]
Between #50 and #130, I consider this issue to be resolved. Clicking will also be involved in moving or deleted cells, but we have separate issues tracking those features.
