### ISSUE TITLE
In the new cell dropdown, why do we have to use alt?

### ISSUE THREAD

**Issue by olynch** [ToposInstitute/CatColab#47]
When we hit shift-enter to create a new cell, we are already in a "mode" where it is not expected that keystrokes would go to the currently selected cell. So why do we have to add "alt" to our next keystroke? It would make sense to select options just by normal keys, i.e. "t", "s", etc.

**Comment by olynch** [comment]
Maybe we could somehow visually emphasize that "alt" has already "logically" been pushed down by writing the "alt +" in "alt + t" in grey.

**Comment by olynch** [comment]
Now that we are going to use the typeahead for selecting, we can retain the alt shortcuts cleanly; typing normally still does something.

**Comment by epatters** [comment]
Resolved by #57.
