### ISSUE TITLE
Visual distinction around cells

### ISSUE THREAD

**Issue by olynch** [ToposInstitute/CatColab#49]
I like the minimalist style for cells. However, it might be good to be *slightly* less minimalist to give some indication of how many cells there were, and what type are the cells. Perhaps rather than a full border, just a border-left? This would also give a visual indicator for where to drag for #19.

**Comment by epatters** [comment]
+1 for border-left only. I had been contemplating that myself, and I agree it would pair nicely with #19.

**Comment by KevinDCarlson** [comment]
Isn't this done?

**Comment by epatters** [comment]
It is done. Thanks for noticing!
