### ISSUE TITLE
New cell logic

### ISSUE THREAD

**Issue by olynch** [ToposInstitute/CatColab#50]
Right now, the logic for the new cell menu is the following.

1. There is a notebook-level boolean signal `isCellMenuOpen`.
2. Whatever the currently-focused cell is looks at that boolean, and if it is true, it opens up the new cell menu.
3. When something is clicked in the new cell menu, a new cell is created.

This leads to the slightly glitchy behavior that if you open up the cell menu, and then shift focus to another cell, the cell menu jumps to the cell that you focused to, before disappearing.

I think it makes more sense to do the following.

1. We can have a "stem cell" cell type, which simply displays a menu of options for cells to transform into. When a stem cell is focused, these options can be selected via keyboard.
2. Hitting shift-enter produces a new stem cell after the current cell, and focuses that stem cell (replicating the current "cellMenu" behavior).
3. We can have "+" buttons between every two cells, and at the beginning and end of the notebook which insert stem cells.

**Comment by epatters** [comment]
Great idea. And it can be built into the `NotebookEditor`, rather than the `ModelEditor`, so that it be reused for other structured objects that will be edited with a notebook-like interface.
